//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyZp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KR_VPKSEntities : DbContext
    {
        public KR_VPKSEntities()
            : base("name=KR_VPKSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        private static KR_VPKSEntities _context;
        public static KR_VPKSEntities GetContext()
        {
            if (_context == null)
                _context = new KR_VPKSEntities();

            return _context;
        }

        public virtual DbSet<Friends> Friends { get; set; }
        public virtual DbSet<FriendStatus> FriendStatus { get; set; }
        public virtual DbSet<Shifts> Shifts { get; set; }
        public virtual DbSet<ShiftTypes> ShiftTypes { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UserShifts> UserShifts { get; set; }
    }
}
