//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyZp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shifts
    {
        public int ID { get; set; }
        public System.TimeSpan Start { get; set; }
        public System.TimeSpan End { get; set; }
        public System.TimeSpan Rate { get; set; }
        public System.TimeSpan PaidTime { get; set; }
        public Nullable<decimal> AdditionalPayment { get; set; }
        public Nullable<decimal> Expenses { get; set; }
        public int ShiftType_ID { get; set; }
    
        public virtual ShiftTypes ShiftTypes { get; set; }
    }
}
